
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Example': typeof import("../components/Example.vue")['default']
    'SharedAccordion': typeof import("../../injective-ui/layer/components/Accordion.vue")['default']
    'SharedAmountCollapsed': typeof import("../../injective-ui/layer/components/AmountCollapsed.vue")['default']
    'SharedAmountFormatter': typeof import("../../injective-ui/layer/components/AmountFormatter.vue")['default']
    'SharedBitMapFilterList': typeof import("../../injective-ui/layer/components/BitMapFilterList.vue")['default']
    'SharedButton': typeof import("../../injective-ui/layer/components/Button.vue")['default']
    'SharedCheckbox': typeof import("../../injective-ui/layer/components/Checkbox.vue")['default']
    'SharedConfetti': typeof import("../../injective-ui/layer/components/Confetti.vue")['default']
    'SharedDatepicker': typeof import("../../injective-ui/layer/components/Datepicker.vue")['default']
    'SharedDropdown': typeof import("../../injective-ui/layer/components/Dropdown.vue")['default']
    'SharedDropdownItem': typeof import("../../injective-ui/layer/components/DropdownItem.vue")['default']
    'SharedHoverMenu': typeof import("../../injective-ui/layer/components/HoverMenu.vue")['default']
    'SharedIcon': typeof import("../../injective-ui/layer/components/Icon.vue")['default']
    'SharedInlineNotification': typeof import("../../injective-ui/layer/components/InlineNotification.vue")['default']
    'SharedInput': typeof import("../../injective-ui/layer/components/Input.vue")['default']
    'SharedLineGraph': typeof import("../../injective-ui/layer/components/LineGraph.vue")['default']
    'SharedModal': typeof import("../../injective-ui/layer/components/Modal.vue")['default']
    'SharedModalWrapper': typeof import("../../injective-ui/layer/components/ModalWrapper.vue")['default']
    'SharedMultiSelect': typeof import("../../injective-ui/layer/components/MultiSelect.vue")['default']
    'SharedNotification': typeof import("../../injective-ui/layer/components/Notification.vue")['default']
    'SharedNotifications': typeof import("../../injective-ui/layer/components/Notifications.vue")['default']
    'SharedNumInput': typeof import("../../injective-ui/layer/components/NumInput.vue")['default']
    'SharedNumericInput': typeof import("../../injective-ui/layer/components/NumericInput.vue")['default']
    'SharedPageConfetti': typeof import("../../injective-ui/layer/components/PageConfetti.vue")['default']
    'SharedPaginationWrapper': typeof import("../../injective-ui/layer/components/PaginationWrapper.vue")['default']
    'SharedQRCode': typeof import("../../injective-ui/layer/components/QRCode.vue")['default']
    'SharedRainConfetti': typeof import("../../injective-ui/layer/components/RainConfetti.vue")['default']
    'SharedSelectorItem': typeof import("../../injective-ui/layer/components/SelectorItem.vue")['default']
    'SharedSortableHeaderItem': typeof import("../../injective-ui/layer/components/SortableHeaderItem.vue")['default']
    'SharedSpinner': typeof import("../../injective-ui/layer/components/Spinner.vue")['default']
    'SharedTextArea': typeof import("../../injective-ui/layer/components/TextArea.vue")['default']
    'SharedTokenSelectMenu': typeof import("../../injective-ui/layer/components/TokenSelectMenu.vue")['default']
    'SharedTokenSelectModal': typeof import("../../injective-ui/layer/components/TokenSelectModal.vue")['default']
    'SharedTooltip': typeof import("../../injective-ui/layer/components/Tooltip.vue")['default']
    'SharedUsdAmount': typeof import("../../injective-ui/layer/components/UsdAmount.vue")['default']
    'SharedWhiteboard': typeof import("../../injective-ui/layer/components/Whiteboard.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'DelayHydration': typeof import("../node_modules/nuxt-vitalizer/dist/runtime/components/DelayHydration")['default']
    'SkipHydration': typeof import("../node_modules/nuxt-vitalizer/dist/runtime/components/SkipHydration")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyExample': typeof import("../components/Example.vue")['default']
    'LazySharedAccordion': typeof import("../../injective-ui/layer/components/Accordion.vue")['default']
    'LazySharedAmountCollapsed': typeof import("../../injective-ui/layer/components/AmountCollapsed.vue")['default']
    'LazySharedAmountFormatter': typeof import("../../injective-ui/layer/components/AmountFormatter.vue")['default']
    'LazySharedBitMapFilterList': typeof import("../../injective-ui/layer/components/BitMapFilterList.vue")['default']
    'LazySharedButton': typeof import("../../injective-ui/layer/components/Button.vue")['default']
    'LazySharedCheckbox': typeof import("../../injective-ui/layer/components/Checkbox.vue")['default']
    'LazySharedConfetti': typeof import("../../injective-ui/layer/components/Confetti.vue")['default']
    'LazySharedDatepicker': typeof import("../../injective-ui/layer/components/Datepicker.vue")['default']
    'LazySharedDropdown': typeof import("../../injective-ui/layer/components/Dropdown.vue")['default']
    'LazySharedDropdownItem': typeof import("../../injective-ui/layer/components/DropdownItem.vue")['default']
    'LazySharedHoverMenu': typeof import("../../injective-ui/layer/components/HoverMenu.vue")['default']
    'LazySharedIcon': typeof import("../../injective-ui/layer/components/Icon.vue")['default']
    'LazySharedInlineNotification': typeof import("../../injective-ui/layer/components/InlineNotification.vue")['default']
    'LazySharedInput': typeof import("../../injective-ui/layer/components/Input.vue")['default']
    'LazySharedLineGraph': typeof import("../../injective-ui/layer/components/LineGraph.vue")['default']
    'LazySharedModal': typeof import("../../injective-ui/layer/components/Modal.vue")['default']
    'LazySharedModalWrapper': typeof import("../../injective-ui/layer/components/ModalWrapper.vue")['default']
    'LazySharedMultiSelect': typeof import("../../injective-ui/layer/components/MultiSelect.vue")['default']
    'LazySharedNotification': typeof import("../../injective-ui/layer/components/Notification.vue")['default']
    'LazySharedNotifications': typeof import("../../injective-ui/layer/components/Notifications.vue")['default']
    'LazySharedNumInput': typeof import("../../injective-ui/layer/components/NumInput.vue")['default']
    'LazySharedNumericInput': typeof import("../../injective-ui/layer/components/NumericInput.vue")['default']
    'LazySharedPageConfetti': typeof import("../../injective-ui/layer/components/PageConfetti.vue")['default']
    'LazySharedPaginationWrapper': typeof import("../../injective-ui/layer/components/PaginationWrapper.vue")['default']
    'LazySharedQRCode': typeof import("../../injective-ui/layer/components/QRCode.vue")['default']
    'LazySharedRainConfetti': typeof import("../../injective-ui/layer/components/RainConfetti.vue")['default']
    'LazySharedSelectorItem': typeof import("../../injective-ui/layer/components/SelectorItem.vue")['default']
    'LazySharedSortableHeaderItem': typeof import("../../injective-ui/layer/components/SortableHeaderItem.vue")['default']
    'LazySharedSpinner': typeof import("../../injective-ui/layer/components/Spinner.vue")['default']
    'LazySharedTextArea': typeof import("../../injective-ui/layer/components/TextArea.vue")['default']
    'LazySharedTokenSelectMenu': typeof import("../../injective-ui/layer/components/TokenSelectMenu.vue")['default']
    'LazySharedTokenSelectModal': typeof import("../../injective-ui/layer/components/TokenSelectModal.vue")['default']
    'LazySharedTooltip': typeof import("../../injective-ui/layer/components/Tooltip.vue")['default']
    'LazySharedUsdAmount': typeof import("../../injective-ui/layer/components/UsdAmount.vue")['default']
    'LazySharedWhiteboard': typeof import("../../injective-ui/layer/components/Whiteboard.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyDelayHydration': typeof import("../node_modules/nuxt-vitalizer/dist/runtime/components/DelayHydration")['default']
    'LazySkipHydration': typeof import("../node_modules/nuxt-vitalizer/dist/runtime/components/SkipHydration")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Example: typeof import("../components/Example.vue")['default']
export const SharedAccordion: typeof import("../../injective-ui/layer/components/Accordion.vue")['default']
export const SharedAmountCollapsed: typeof import("../../injective-ui/layer/components/AmountCollapsed.vue")['default']
export const SharedAmountFormatter: typeof import("../../injective-ui/layer/components/AmountFormatter.vue")['default']
export const SharedBitMapFilterList: typeof import("../../injective-ui/layer/components/BitMapFilterList.vue")['default']
export const SharedButton: typeof import("../../injective-ui/layer/components/Button.vue")['default']
export const SharedCheckbox: typeof import("../../injective-ui/layer/components/Checkbox.vue")['default']
export const SharedConfetti: typeof import("../../injective-ui/layer/components/Confetti.vue")['default']
export const SharedDatepicker: typeof import("../../injective-ui/layer/components/Datepicker.vue")['default']
export const SharedDropdown: typeof import("../../injective-ui/layer/components/Dropdown.vue")['default']
export const SharedDropdownItem: typeof import("../../injective-ui/layer/components/DropdownItem.vue")['default']
export const SharedHoverMenu: typeof import("../../injective-ui/layer/components/HoverMenu.vue")['default']
export const SharedIcon: typeof import("../../injective-ui/layer/components/Icon.vue")['default']
export const SharedInlineNotification: typeof import("../../injective-ui/layer/components/InlineNotification.vue")['default']
export const SharedInput: typeof import("../../injective-ui/layer/components/Input.vue")['default']
export const SharedLineGraph: typeof import("../../injective-ui/layer/components/LineGraph.vue")['default']
export const SharedModal: typeof import("../../injective-ui/layer/components/Modal.vue")['default']
export const SharedModalWrapper: typeof import("../../injective-ui/layer/components/ModalWrapper.vue")['default']
export const SharedMultiSelect: typeof import("../../injective-ui/layer/components/MultiSelect.vue")['default']
export const SharedNotification: typeof import("../../injective-ui/layer/components/Notification.vue")['default']
export const SharedNotifications: typeof import("../../injective-ui/layer/components/Notifications.vue")['default']
export const SharedNumInput: typeof import("../../injective-ui/layer/components/NumInput.vue")['default']
export const SharedNumericInput: typeof import("../../injective-ui/layer/components/NumericInput.vue")['default']
export const SharedPageConfetti: typeof import("../../injective-ui/layer/components/PageConfetti.vue")['default']
export const SharedPaginationWrapper: typeof import("../../injective-ui/layer/components/PaginationWrapper.vue")['default']
export const SharedQRCode: typeof import("../../injective-ui/layer/components/QRCode.vue")['default']
export const SharedRainConfetti: typeof import("../../injective-ui/layer/components/RainConfetti.vue")['default']
export const SharedSelectorItem: typeof import("../../injective-ui/layer/components/SelectorItem.vue")['default']
export const SharedSortableHeaderItem: typeof import("../../injective-ui/layer/components/SortableHeaderItem.vue")['default']
export const SharedSpinner: typeof import("../../injective-ui/layer/components/Spinner.vue")['default']
export const SharedTextArea: typeof import("../../injective-ui/layer/components/TextArea.vue")['default']
export const SharedTokenSelectMenu: typeof import("../../injective-ui/layer/components/TokenSelectMenu.vue")['default']
export const SharedTokenSelectModal: typeof import("../../injective-ui/layer/components/TokenSelectModal.vue")['default']
export const SharedTooltip: typeof import("../../injective-ui/layer/components/Tooltip.vue")['default']
export const SharedUsdAmount: typeof import("../../injective-ui/layer/components/UsdAmount.vue")['default']
export const SharedWhiteboard: typeof import("../../injective-ui/layer/components/Whiteboard.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const DelayHydration: typeof import("../node_modules/nuxt-vitalizer/dist/runtime/components/DelayHydration")['default']
export const SkipHydration: typeof import("../node_modules/nuxt-vitalizer/dist/runtime/components/SkipHydration")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyExample: typeof import("../components/Example.vue")['default']
export const LazySharedAccordion: typeof import("../../injective-ui/layer/components/Accordion.vue")['default']
export const LazySharedAmountCollapsed: typeof import("../../injective-ui/layer/components/AmountCollapsed.vue")['default']
export const LazySharedAmountFormatter: typeof import("../../injective-ui/layer/components/AmountFormatter.vue")['default']
export const LazySharedBitMapFilterList: typeof import("../../injective-ui/layer/components/BitMapFilterList.vue")['default']
export const LazySharedButton: typeof import("../../injective-ui/layer/components/Button.vue")['default']
export const LazySharedCheckbox: typeof import("../../injective-ui/layer/components/Checkbox.vue")['default']
export const LazySharedConfetti: typeof import("../../injective-ui/layer/components/Confetti.vue")['default']
export const LazySharedDatepicker: typeof import("../../injective-ui/layer/components/Datepicker.vue")['default']
export const LazySharedDropdown: typeof import("../../injective-ui/layer/components/Dropdown.vue")['default']
export const LazySharedDropdownItem: typeof import("../../injective-ui/layer/components/DropdownItem.vue")['default']
export const LazySharedHoverMenu: typeof import("../../injective-ui/layer/components/HoverMenu.vue")['default']
export const LazySharedIcon: typeof import("../../injective-ui/layer/components/Icon.vue")['default']
export const LazySharedInlineNotification: typeof import("../../injective-ui/layer/components/InlineNotification.vue")['default']
export const LazySharedInput: typeof import("../../injective-ui/layer/components/Input.vue")['default']
export const LazySharedLineGraph: typeof import("../../injective-ui/layer/components/LineGraph.vue")['default']
export const LazySharedModal: typeof import("../../injective-ui/layer/components/Modal.vue")['default']
export const LazySharedModalWrapper: typeof import("../../injective-ui/layer/components/ModalWrapper.vue")['default']
export const LazySharedMultiSelect: typeof import("../../injective-ui/layer/components/MultiSelect.vue")['default']
export const LazySharedNotification: typeof import("../../injective-ui/layer/components/Notification.vue")['default']
export const LazySharedNotifications: typeof import("../../injective-ui/layer/components/Notifications.vue")['default']
export const LazySharedNumInput: typeof import("../../injective-ui/layer/components/NumInput.vue")['default']
export const LazySharedNumericInput: typeof import("../../injective-ui/layer/components/NumericInput.vue")['default']
export const LazySharedPageConfetti: typeof import("../../injective-ui/layer/components/PageConfetti.vue")['default']
export const LazySharedPaginationWrapper: typeof import("../../injective-ui/layer/components/PaginationWrapper.vue")['default']
export const LazySharedQRCode: typeof import("../../injective-ui/layer/components/QRCode.vue")['default']
export const LazySharedRainConfetti: typeof import("../../injective-ui/layer/components/RainConfetti.vue")['default']
export const LazySharedSelectorItem: typeof import("../../injective-ui/layer/components/SelectorItem.vue")['default']
export const LazySharedSortableHeaderItem: typeof import("../../injective-ui/layer/components/SortableHeaderItem.vue")['default']
export const LazySharedSpinner: typeof import("../../injective-ui/layer/components/Spinner.vue")['default']
export const LazySharedTextArea: typeof import("../../injective-ui/layer/components/TextArea.vue")['default']
export const LazySharedTokenSelectMenu: typeof import("../../injective-ui/layer/components/TokenSelectMenu.vue")['default']
export const LazySharedTokenSelectModal: typeof import("../../injective-ui/layer/components/TokenSelectModal.vue")['default']
export const LazySharedTooltip: typeof import("../../injective-ui/layer/components/Tooltip.vue")['default']
export const LazySharedUsdAmount: typeof import("../../injective-ui/layer/components/UsdAmount.vue")['default']
export const LazySharedWhiteboard: typeof import("../../injective-ui/layer/components/Whiteboard.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyDelayHydration: typeof import("../node_modules/nuxt-vitalizer/dist/runtime/components/DelayHydration")['default']
export const LazySkipHydration: typeof import("../node_modules/nuxt-vitalizer/dist/runtime/components/SkipHydration")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
